/* Weighted bilingual search with synonyms, popular queries, and fallbacks. */
(function(){
  var input=document.getElementById('site-search-input');if(!input)return;
  var isEn=location.pathname.indexOf('/en/')!==-1;
  var prefix=document.body.getAttribute('data-kb-root');if(prefix===null)prefix=isEn?'../':'';
  var data=[];
  var synonyms=[
    ['积分','credits','credit','流量费'],['会员','vip','l4','100x','nft'],['人工智能','ai','策略引擎','strategy engine'],
    ['信号','signal'],['苏醒','wake-up','wake up','awakening'],['早期精选','early selection'],['战壕','trench'],
    ['看板','board','dashboard'],['代币','token','币'],['市值','market cap','mcap'],['价格','price'],
    ['止损','stop loss','sl'],['止盈','take profit','tp'],['网格','grid'],['导入','import'],['异常','error','issue','故障'],
    ['复盘','recap','review'],['设置','settings','配置','configure'],['上下文','ctx','context']
  ];
  var popular=isEn?['AI strategy','Credits','Wake-up signal','Import strategy','Token page']:['AI 策略','Credits','苏醒信号','导入策略','代币详情页'];
  var box=document.createElement('div');box.className='site-search-results';input.parentNode.appendChild(box);
  var style=document.createElement('style');style.textContent='.site-search{position:relative;max-width:520px}.site-search input{width:100%;box-sizing:border-box;background:var(--bg-card,#121512);border:1px solid var(--line,#24302a);border-radius:10px;color:var(--text,#e9efe9);font-size:14px;padding:11px 14px;outline:none}.site-search-results{position:absolute;left:0;right:0;top:calc(100% + 6px);z-index:70;background:var(--bg-card,#121512);border:1px solid var(--line,#24302a);border-radius:10px;overflow:auto;box-shadow:0 12px 28px rgba(0,0,0,.35);display:none;max-height:440px}.site-search-results a{display:block;padding:10px 14px;text-decoration:none;border-bottom:1px solid var(--line,#24302a);color:var(--text,#e9efe9)}.site-search-results a:hover{background:var(--bg-card-2,#171b17)}.site-search-results small{display:block;color:var(--text-faint,#718075);margin-top:2px}.site-search-lang{float:right;color:var(--green,#3ddc84);font-size:10px}.site-search-empty,.site-search-popular{padding:14px;color:var(--text-faint,#718075);font-size:13px}.site-search-popular button{border:1px solid var(--line,#24302a);border-radius:999px;background:transparent;color:var(--text-dim,#8ea092);padding:5px 9px;margin:8px 5px 0 0;cursor:pointer}.site-search-popular button:hover{border-color:var(--green-dim,#1f5c3f);color:var(--text,#e9efe9)}.site-search-actions{display:flex;gap:8px;margin-top:10px}.site-search-actions a{display:inline-block;border:1px solid var(--line,#24302a);border-radius:7px;padding:6px 9px;font-size:12px}mark{background:rgba(61,220,132,.22);color:inherit}';document.head.appendChild(style);
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function rawTerms(q){return q.toLowerCase().trim().split(/\s+/).filter(Boolean)}
  function expanded(q){var base=rawTerms(q),out=base.slice();synonyms.forEach(function(group){if(group.some(function(x){return base.indexOf(x)>=0||q.toLowerCase().indexOf(x)>=0}))group.forEach(function(x){if(out.indexOf(x)<0)out.push(x)})});return{base:base,all:out}}
  function results(q){var ts=expanded(q);if(!ts.base.length)return[];return data.map(function(x){var title=x.title.toLowerCase(),heading=x.heading.toLowerCase(),body=x.text.toLowerCase(),score=0,matched=0;ts.all.forEach(function(t){var hit=false;if(title.indexOf(t)>=0){score+=12;hit=true}if(heading.indexOf(t)>=0){score+=7;hit=true}if(body.indexOf(t)>=0){score+=2;hit=true}if(hit&&ts.base.indexOf(t)>=0)matched++});if(x.lang===(isEn?'en':'zh'))score+=1;return{x:x,score:score,matched:matched}}).filter(function(r){return r.score>0}).sort(function(a,b){return b.score-a.score}).slice(0,12)}
  function snippet(text,q){var list=expanded(q).all,t=list.find(function(k){return text.toLowerCase().indexOf(k)>=0})||list[0],at=text.toLowerCase().indexOf(t),start=Math.max(0,at-45),s=text.slice(start,start+130);if(start)s='…'+s;rawTerms(q).forEach(function(k){s=s.replace(new RegExp('('+k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','ig'),'<mark>$1</mark>')});return s}
  function href(x){return prefix+(x.lang==='en'?'en/':'')+x.url}
  function popularHtml(){return'<div class="site-search-popular">'+(isEn?'Popular searches':'热门搜索')+'<div>'+popular.map(function(q){return'<button type="button" data-query="'+esc(q)+'">'+esc(q)+'</button>'}).join('')+'</div></div>'}
  function render(){var q=input.value.trim();if(!q){box.innerHTML=popularHtml();box.style.display='block';return}var rs=results(q);if(!rs.length){var faq=prefix+(isEn?'en/faq.html':'faq.html'),issue='https://github.com/dinnelthai/logearn-acc/issues/new?title='+encodeURIComponent((isEn?'Missing documentation: ':'缺少文档：')+q);box.innerHTML='<div class="site-search-empty">'+(isEn?'No matching content. Try FAQ or tell us what is missing.':'没有匹配内容，可以查看 FAQ 或告诉我们缺少什么。')+'<div class="site-search-actions"><a href="'+faq+'">FAQ</a><a href="'+issue+'" target="_blank" rel="noopener">'+(isEn?'Send feedback':'提交反馈')+'</a></div></div>'}else{box.innerHTML=rs.map(function(r){var x=r.x;return'<a href="'+href(x)+'"><span class="site-search-lang">'+(x.lang==='en'?'EN':'中文')+'</span><strong>'+esc(x.heading)+'</strong><small>'+esc(x.title)+' · '+snippet(esc(x.text),q)+'</small></a>'}).join('')}box.style.display='block'}
  Promise.all(['zh','en'].map(function(lang){return fetch(prefix+'search-index.'+lang+'.json').then(function(r){return r.json()}).then(function(items){items.forEach(function(x){x.lang=lang});return items})})).then(function(groups){data=groups[0].concat(groups[1])}).catch(function(){box.innerHTML='<div class="site-search-empty">'+(isEn?'Search is temporarily unavailable.':'搜索暂时不可用。')+'</div>'});
  box.addEventListener('click',function(e){var b=e.target.closest('[data-query]');if(b){input.value=b.getAttribute('data-query');render();input.focus()}});
  input.addEventListener('input',render);input.addEventListener('focus',render);input.addEventListener('keydown',function(e){if(e.key==='Enter'){var a=box.querySelector('a');if(a)location.href=a.href}if(e.key==='Escape')box.style.display='none'});document.addEventListener('click',function(e){if(!input.parentNode.contains(e.target))box.style.display='none'});
})();
